package entities;
// Generated Apr 26, 2017 3:11:57 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotBlank;

/**
 * Depart generated by hbm2java
 */
@Entity
@Table(name = "depart", catalog = "personal")
public class Depart implements java.io.Serializable {
	
	@NotBlank(message = "You must fill out this field")
	private String departId;
	
	@NotBlank(message = "You must fill out this field")
	private String name;
	private Set<Staff> staffs = new HashSet<Staff>(0);

	public Depart() {
	}

	public Depart(String departId, String name) {
		this.departId = departId;
		this.name = name;
	}

	public Depart(String departId, String name, Set<Staff> staffs) {
		this.departId = departId;
		this.name = name;
		this.staffs = staffs;
	}

	@Id

	@Column(name = "DepartId", unique = true, nullable = false, length = 10)
	public String getDepartId() {
		return this.departId;
	}

	public void setDepartId(String departId) {
		this.departId = departId;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "depart")
	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}



}
