package entities;
// Generated Apr 26, 2017 3:11:57 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "personal")
public class User implements java.io.Serializable {

	@Length(min = 6, message="Username is at least 6 digits")
	private String username;
	
	@Length(min = 6, message="Username is at least 6 digits")
	private String password;
	
	@NotBlank(message = "You must type in your name")
	private String fullname;
	
	@NotNull(message = "You must check the radio button")
	private Boolean role;

	public User() {
	}

	public User(String username, String password, String fullname) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
	}

	public User(String username, String password, String fullname, Boolean role) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.role = role;
	}

	@Id

	@Column(name = "Username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Fullname", nullable = false, length = 50)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "Role")
	public Boolean getRole() {
		return this.role;
	}

	public void setRole(Boolean role) {
		this.role = role;
	}

}
